my_new_project:
  outputs:
    dev:
      account: fka50167
      database: analytics
      password: <fill-me-in>
      role: Transformer
      schema: <fill-me-in>
      threads: 4
      type: snowflake
      user: <fill-me-in>
      warehouse: transforming
  target: dev
